# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.control_panel = QtWidgets.QWidget(self.splitter)
        self.control_panel.setObjectName("control_panel")
        self.control_layout = QtWidgets.QVBoxLayout(self.control_panel)
        self.control_layout.setContentsMargins(0, 0, 0, 0)
        self.control_layout.setObjectName("control_layout")
        self.connection_group = QtWidgets.QGroupBox(self.control_panel)
        self.connection_group.setObjectName("connection_group")
        self.connection_form = QtWidgets.QFormLayout(self.connection_group)
        self.connection_form.setObjectName("connection_form")
        self.platform_label = QtWidgets.QLabel(self.connection_group)
        self.platform_label.setObjectName("platform_label")
        self.connection_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.platform_label)
        self.platform_combo = QtWidgets.QComboBox(self.connection_group)
        self.platform_combo.setObjectName("platform_combo")
        self.platform_combo.addItem("")
        self.platform_combo.addItem("")
        self.platform_combo.addItem("")
        self.connection_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.platform_combo)
        self.device_id_label = QtWidgets.QLabel(self.connection_group)
        self.device_id_label.setObjectName("device_id_label")
        self.connection_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.device_id_label)
        self.device_id_edit = QtWidgets.QLineEdit(self.connection_group)
        self.device_id_edit.setObjectName("device_id_edit")
        self.connection_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.device_id_edit)
        self.adb_path_label = QtWidgets.QLabel(self.connection_group)
        self.adb_path_label.setObjectName("adb_path_label")
        self.connection_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.adb_path_label)
        self.adb_layout = QtWidgets.QHBoxLayout()
        self.adb_layout.setObjectName("adb_layout")
        self.adb_path_edit = QtWidgets.QLineEdit(self.connection_group)
        self.adb_path_edit.setObjectName("adb_path_edit")
        self.adb_layout.addWidget(self.adb_path_edit)
        self.adb_path_browse = QtWidgets.QPushButton(self.connection_group)
        self.adb_path_browse.setObjectName("adb_path_browse")
        self.adb_layout.addWidget(self.adb_path_browse)
        self.connection_form.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.adb_layout)
        self.connect_btn = QtWidgets.QPushButton(self.connection_group)
        self.connect_btn.setObjectName("connect_btn")
        self.connection_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.connect_btn)
        self.control_layout.addWidget(self.connection_group)
        self.collection_group = QtWidgets.QGroupBox(self.control_panel)
        self.collection_group.setObjectName("collection_group")
        self.collection_layout = QtWidgets.QVBoxLayout(self.collection_group)
        self.collection_layout.setObjectName("collection_layout")
        self.collection_buttons = QtWidgets.QHBoxLayout()
        self.collection_buttons.setObjectName("collection_buttons")
        self.start_collect_btn = QtWidgets.QPushButton(self.collection_group)
        self.start_collect_btn.setEnabled(False)
        self.start_collect_btn.setObjectName("start_collect_btn")
        self.collection_buttons.addWidget(self.start_collect_btn)
        self.stop_collect_btn = QtWidgets.QPushButton(self.collection_group)
        self.stop_collect_btn.setEnabled(False)
        self.stop_collect_btn.setObjectName("stop_collect_btn")
        self.collection_buttons.addWidget(self.stop_collect_btn)
        self.collection_layout.addLayout(self.collection_buttons)
        self.progress_bar = QtWidgets.QProgressBar(self.collection_group)
        self.progress_bar.setVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.collection_layout.addWidget(self.progress_bar)
        self.status_label = QtWidgets.QLabel(self.collection_group)
        self.status_label.setObjectName("status_label")
        self.collection_layout.addWidget(self.status_label)
        self.control_layout.addWidget(self.collection_group)
        self.export_group = QtWidgets.QGroupBox(self.control_panel)
        self.export_group.setObjectName("export_group")
        self.export_layout = QtWidgets.QVBoxLayout(self.export_group)
        self.export_layout.setObjectName("export_layout")
        self.export_btn = QtWidgets.QPushButton(self.export_group)
        self.export_btn.setEnabled(False)
        self.export_btn.setObjectName("export_btn")
        self.export_layout.addWidget(self.export_btn)
        self.auto_open_check = QtWidgets.QCheckBox(self.export_group)
        self.auto_open_check.setObjectName("auto_open_check")
        self.export_layout.addWidget(self.auto_open_check)
        self.control_layout.addWidget(self.export_group)
        self.settings_group = QtWidgets.QGroupBox(self.control_panel)
        self.settings_group.setObjectName("settings_group")
        self.settings_form = QtWidgets.QFormLayout(self.settings_group)
        self.settings_form.setObjectName("settings_form")
        self.ocr_engine_label = QtWidgets.QLabel(self.settings_group)
        self.ocr_engine_label.setObjectName("ocr_engine_label")
        self.settings_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ocr_engine_label)
        self.ocr_engine_combo = QtWidgets.QComboBox(self.settings_group)
        self.ocr_engine_combo.setObjectName("ocr_engine_combo")
        self.ocr_engine_combo.addItem("")
        self.ocr_engine_combo.addItem("")
        self.settings_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ocr_engine_combo)
        self.confidence_label = QtWidgets.QLabel(self.settings_group)
        self.confidence_label.setObjectName("confidence_label")
        self.settings_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.confidence_label)
        self.confidence_spin = QtWidgets.QDoubleSpinBox(self.settings_group)
        self.confidence_spin.setMinimum(0.1)
        self.confidence_spin.setMaximum(1.0)
        self.confidence_spin.setSingleStep(0.1)
        self.confidence_spin.setObjectName("confidence_spin")
        self.settings_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.confidence_spin)
        self.delay_label = QtWidgets.QLabel(self.settings_group)
        self.delay_label.setObjectName("delay_label")
        self.settings_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.delay_label)
        self.delay_spin = QtWidgets.QDoubleSpinBox(self.settings_group)
        self.delay_spin.setMinimum(0.5)
        self.delay_spin.setMaximum(10.0)
        self.delay_spin.setSingleStep(0.5)
        self.delay_spin.setObjectName("delay_spin")
        self.settings_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.delay_spin)
        self.debug_check = QtWidgets.QCheckBox(self.settings_group)
        self.debug_check.setObjectName("debug_check")
        self.settings_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.debug_check)
        self.control_layout.addWidget(self.settings_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.control_layout.addItem(spacerItem)
        self.data_panel = QtWidgets.QWidget(self.splitter)
        self.data_panel.setObjectName("data_panel")
        self.data_layout = QtWidgets.QVBoxLayout(self.data_panel)
        self.data_layout.setContentsMargins(0, 0, 0, 0)
        self.data_layout.setObjectName("data_layout")
        self.tab_widget = QtWidgets.QTabWidget(self.data_panel)
        self.tab_widget.setObjectName("tab_widget")
        self.generals_tab = QtWidgets.QWidget()
        self.generals_tab.setObjectName("generals_tab")
        self.generals_layout = QtWidgets.QVBoxLayout(self.generals_tab)
        self.generals_layout.setObjectName("generals_layout")
        self.stats_layout = QtWidgets.QHBoxLayout()
        self.stats_layout.setObjectName("stats_layout")
        self.total_label = QtWidgets.QLabel(self.generals_tab)
        self.total_label.setObjectName("total_label")
        self.stats_layout.addWidget(self.total_label)
        self.uncertain_label = QtWidgets.QLabel(self.generals_tab)
        self.uncertain_label.setObjectName("uncertain_label")
        self.stats_layout.addWidget(self.uncertain_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stats_layout.addItem(spacerItem1)
        self.generals_layout.addLayout(self.stats_layout)
        self.generals_table = QtWidgets.QTableWidget(self.generals_tab)
        self.generals_table.setAlternatingRowColors(True)
        self.generals_table.setColumnCount(3)
        self.generals_table.setObjectName("generals_table")
        self.generals_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.generals_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.generals_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.generals_table.setHorizontalHeaderItem(2, item)
        self.generals_table.horizontalHeader().setStretchLastSection(True)
        self.generals_layout.addWidget(self.generals_table)
        self.tab_widget.addTab(self.generals_tab, "")
        self.progress_tab = QtWidgets.QWidget()
        self.progress_tab.setObjectName("progress_tab")
        self.progress_layout = QtWidgets.QVBoxLayout(self.progress_tab)
        self.progress_layout.setObjectName("progress_layout")
        self.current_progress_group = QtWidgets.QGroupBox(self.progress_tab)
        self.current_progress_group.setObjectName("current_progress_group")
        self.progress_form = QtWidgets.QFormLayout(self.current_progress_group)
        self.progress_form.setObjectName("progress_form")
        self.progress_general_label_text = QtWidgets.QLabel(self.current_progress_group)
        self.progress_general_label_text.setObjectName("progress_general_label_text")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.progress_general_label_text)
        self.progress_general_label = QtWidgets.QLabel(self.current_progress_group)
        self.progress_general_label.setObjectName("progress_general_label")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progress_general_label)
        self.progress_step_label_text = QtWidgets.QLabel(self.current_progress_group)
        self.progress_step_label_text.setObjectName("progress_step_label_text")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.progress_step_label_text)
        self.progress_step_label = QtWidgets.QLabel(self.current_progress_group)
        self.progress_step_label.setText("")
        self.progress_step_label.setObjectName("progress_step_label")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progress_step_label)
        self.progress_status_label_text = QtWidgets.QLabel(self.current_progress_group)
        self.progress_status_label_text.setObjectName("progress_status_label_text")
        self.progress_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.progress_status_label_text)
        self.progress_status_label = QtWidgets.QLabel(self.current_progress_group)
        self.progress_status_label.setObjectName("progress_status_label")
        self.progress_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.progress_status_label)
        self.progress_bar_label = QtWidgets.QLabel(self.current_progress_group)
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.progress_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.progress_bar_label)
        self.progress_bar_detailed = QtWidgets.QProgressBar(self.current_progress_group)
        self.progress_bar_detailed.setObjectName("progress_bar_detailed")
        self.progress_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.progress_bar_detailed)
        self.progress_layout.addWidget(self.current_progress_group)
        self.statistics_group = QtWidgets.QGroupBox(self.progress_tab)
        self.statistics_group.setObjectName("statistics_group")
        self.stats_form = QtWidgets.QFormLayout(self.statistics_group)
        self.stats_form.setObjectName("stats_form")
        self.elapsed_time_label_text = QtWidgets.QLabel(self.statistics_group)
        self.elapsed_time_label_text.setObjectName("elapsed_time_label_text")
        self.stats_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.elapsed_time_label_text)
        self.elapsed_time_label = QtWidgets.QLabel(self.statistics_group)
        self.elapsed_time_label.setObjectName("elapsed_time_label")
        self.stats_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.elapsed_time_label)
        self.estimated_time_label_text = QtWidgets.QLabel(self.statistics_group)
        self.estimated_time_label_text.setObjectName("estimated_time_label_text")
        self.stats_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.estimated_time_label_text)
        self.estimated_time_label = QtWidgets.QLabel(self.statistics_group)
        self.estimated_time_label.setObjectName("estimated_time_label")
        self.stats_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.estimated_time_label)
        self.average_confidence_label_text = QtWidgets.QLabel(self.statistics_group)
        self.average_confidence_label_text.setObjectName("average_confidence_label_text")
        self.stats_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.average_confidence_label_text)
        self.average_confidence_label = QtWidgets.QLabel(self.statistics_group)
        self.average_confidence_label.setObjectName("average_confidence_label")
        self.stats_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.average_confidence_label)
        self.progress_layout.addWidget(self.statistics_group)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.progress_layout.addItem(spacerItem2)
        self.tab_widget.addTab(self.progress_tab, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.log_layout = QtWidgets.QVBoxLayout(self.log_tab)
        self.log_layout.setObjectName("log_layout")
        self.log_controls = QtWidgets.QHBoxLayout()
        self.log_controls.setObjectName("log_controls")
        self.clear_log_btn = QtWidgets.QPushButton(self.log_tab)
        self.clear_log_btn.setObjectName("clear_log_btn")
        self.log_controls.addWidget(self.clear_log_btn)
        self.save_log_btn = QtWidgets.QPushButton(self.log_tab)
        self.save_log_btn.setObjectName("save_log_btn")
        self.log_controls.addWidget(self.save_log_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.log_controls.addItem(spacerItem3)
        self.log_layout.addLayout(self.log_controls)
        self.log_display = QtWidgets.QTextEdit(self.log_tab)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        self.log_display.setFont(font)
        self.log_display.setReadOnly(True)
        self.log_display.setObjectName("log_display")
        self.log_layout.addWidget(self.log_display)
        self.tab_widget.addTab(self.log_tab, "")
        self.data_layout.addWidget(self.tab_widget)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTestConnection = QtWidgets.QAction(MainWindow)
        self.actionTestConnection.setObjectName("actionTestConnection")
        self.actionGeneralsTab = QtWidgets.QAction(MainWindow)
        self.actionGeneralsTab.setObjectName("actionGeneralsTab")
        self.actionProgressTab = QtWidgets.QAction(MainWindow)
        self.actionProgressTab.setObjectName("actionProgressTab")
        self.actionLogsTab = QtWidgets.QAction(MainWindow)
        self.actionLogsTab.setObjectName("actionLogsTab")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionTestConnection)
        self.menuView.addAction(self.actionGeneralsTab)
        self.menuView.addAction(self.actionProgressTab)
        self.menuView.addAction(self.actionLogsTab)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Evony Active Generals Tracker"))
        MainWindow.setStyleSheet(_translate("MainWindow", "QMainWindow {\n"
"    background-color: #1e1e2e;\n"
"    color: #cdd6f4;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #1e1e2e;\n"
"    color: #cdd6f4;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #45475a;\n"
"    border-radius: 8px;\n"
"    margin-top: 1ex;\n"
"    background-color: #313244;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 10px 0 10px;\n"
"    color: #89b4fa;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #cdd6f4;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {\n"
"    background-color: #45475a;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #585b70;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    selection-background-color: #89b4fa;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border-color: #89b4fa;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background-color: #585b70;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png);\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #45475a;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #585b70;\n"
"    selection-background-color: #89b4fa;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #45475a;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #585b70;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #585b70;\n"
"    border-color: #89b4fa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #313244;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #313244;\n"
"    color: #6c7086;\n"
"    border-color: #313244;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #585b70;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    background-color: #313244;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #89b4fa, stop:1 #f38ba8);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #45475a;\n"
"    background-color: #1e1e2e;\n"
"    alternate-background-color: #313244;\n"
"    selection-background-color: #89b4fa;\n"
"    selection-color: #1e1e2e;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #45475a;\n"
"    color: #cdd6f4;\n"
"    padding: 8px;\n"
"    border: 1px solid #585b70;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #45475a;\n"
"    background-color: #1e1e2e;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #313244;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #45475a;\n"
"    padding: 8px 16px;\n"
"    margin-right: 2px;\n"
"    border-radius: 4px 4px 0 0;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #45475a;\n"
"    color: #89b4fa;\n"
"    border-bottom-color: #45475a;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #585b70;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    background-color: #1e1e2e;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #585b70;\n"
"    border-radius: 4px;\n"
"    font-family: \"Consolas\", \"Monaco\", monospace;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #cdd6f4;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #585b70;\n"
"    border-radius: 3px;\n"
"    background-color: #45475a;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #89b4fa;\n"
"    border-color: #89b4fa;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #89b4fa;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #45475a;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    width: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    height: 2px;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #313244;\n"
"    color: #cdd6f4;\n"
"    border-top: 1px solid #45475a;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #1e1e2e;\n"
"    color: #cdd6f4;\n"
"    border-bottom: 1px solid #45475a;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #45475a;\n"
"    color: #89b4fa;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #313244;\n"
"    color: #cdd6f4;\n"
"    border: 1px solid #45475a;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 4px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #45475a;\n"
"    color: #89b4fa;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #45475a;\n"
"    margin: 2px 0;\n"
"}"))
        self.connection_group.setTitle(_translate("MainWindow", "Platform Connection"))
        self.platform_label.setText(_translate("MainWindow", "Platform:"))
        self.platform_combo.setItemText(0, _translate("MainWindow", "bluestacks"))
        self.platform_combo.setItemText(1, _translate("MainWindow", "android"))
        self.platform_combo.setItemText(2, _translate("MainWindow", "ios"))
        self.device_id_label.setText(_translate("MainWindow", "Device ID:"))
        self.adb_path_label.setText(_translate("MainWindow", "ADB Path:"))
        self.adb_path_browse.setText(_translate("MainWindow", "Browse"))
        self.connect_btn.setText(_translate("MainWindow", "Connect"))
        self.collection_group.setTitle(_translate("MainWindow", "Data Collection"))
        self.start_collect_btn.setText(_translate("MainWindow", "Start Collection"))
        self.stop_collect_btn.setText(_translate("MainWindow", "Stop"))
        self.status_label.setText(_translate("MainWindow", "Idle"))
        self.export_group.setTitle(_translate("MainWindow", "Export"))
        self.export_btn.setText(_translate("MainWindow", "Export to Excel"))
        self.auto_open_check.setText(_translate("MainWindow", "Auto-open Excel file"))
        self.settings_group.setTitle(_translate("MainWindow", "Settings"))
        self.ocr_engine_label.setText(_translate("MainWindow", "OCR Engine:"))
        self.ocr_engine_combo.setItemText(0, _translate("MainWindow", "easyocr"))
        self.ocr_engine_combo.setItemText(1, _translate("MainWindow", "tesseract"))
        self.confidence_label.setText(_translate("MainWindow", "Confidence Threshold:"))
        self.delay_label.setText(_translate("MainWindow", "Transition Delay (s):"))
        self.debug_check.setText(_translate("MainWindow", "Debug Mode"))
        self.total_label.setText(_translate("MainWindow", "Total: 0"))
        self.uncertain_label.setText(_translate("MainWindow", "Uncertain: 0"))
        item = self.generals_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.generals_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Power"))
        item = self.generals_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Uncertain"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.generals_tab), _translate("MainWindow", "Generals Data"))
        self.current_progress_group.setTitle(_translate("MainWindow", "Current Progress"))
        self.progress_general_label_text.setText(_translate("MainWindow", "General:"))
        self.progress_general_label.setText(_translate("MainWindow", "0 / 0"))
        self.progress_step_label_text.setText(_translate("MainWindow", "Current Step:"))
        self.progress_status_label_text.setText(_translate("MainWindow", "Status:"))
        self.progress_status_label.setText(_translate("MainWindow", "Idle"))
        self.progress_bar_label.setText(_translate("MainWindow", "Progress:"))
        self.statistics_group.setTitle(_translate("MainWindow", "Statistics"))
        self.elapsed_time_label_text.setText(_translate("MainWindow", "Elapsed Time:"))
        self.elapsed_time_label.setText(_translate("MainWindow", "0 seconds"))
        self.estimated_time_label_text.setText(_translate("MainWindow", "Estimated Remaining:"))
        self.estimated_time_label.setText(_translate("MainWindow", "Unknown"))
        self.average_confidence_label_text.setText(_translate("MainWindow", "Average Confidence:"))
        self.average_confidence_label.setText(_translate("MainWindow", "0%"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.progress_tab), _translate("MainWindow", "Progress"))
        self.clear_log_btn.setText(_translate("MainWindow", "Clear Log"))
        self.save_log_btn.setText(_translate("MainWindow", "Save Log"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.log_tab), _translate("MainWindow", "Logs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExport.setText(_translate("MainWindow", "Export Data..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionTestConnection.setText(_translate("MainWindow", "Test Connection"))
        self.actionGeneralsTab.setText(_translate("MainWindow", "Generals Tab"))
        self.actionProgressTab.setText(_translate("MainWindow", "Progress Tab"))
        self.actionLogsTab.setText(_translate("MainWindow", "Logs Tab"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
